<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="http://192.168.18.178:3000/users/getuserInfo?id=2"></script>
</head>

<body>
  <div class="box">
  </div>
</body>
<script>
  var sleep = function (time) {
    return new Promise(function (resolve, reject) {
      setTimeout(function () {
        reject({result:'error'});
      }, time);
    })
  };
  var start = async function () {
    try {
      console.log('start');
      let data = await sleep(3000); // 这里得到了一个返回错误
      console.log('data:' + data);
      // 所以以下代码不会被执行了
      console.log('end');
    } catch (data) {
      console.log(data.result); // 这里捕捉到错误 `error`
    }
  };

  start();
</script>

</html>